name = "Bound to Matter"
version = "Playtest 3 - v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7a3be2005e03a458cb9873d12281f0530997f29ace9f23a853acbf01596631c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
