name = "Bound to Matter"
version = "Playtest 4 - v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62792e9d5f6ad3454e1bef54bf4dde0154fddf2d68d2f9fbc8af0f52daac2dd7"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
