name = "Bound to Matter"
version = "Playtest 4 - v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9321de1a5cb1673719c3a8fc016989e38eb0cdf5d7b2370f7c400b5d40cd9f"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["list"]
