[scheduler]
	enabled = true
	interval_ticks = 1200
	spawn_chance = 0.95
	overworld_only = true
	allow_creative_players = true
	skip_spectator_players = true
	disable_vanilla_patrol_spawning = true

[placement]
	min_radius = 32
	max_radius = 64
	spawn_attempts = 24
	max_active_near_player = 48
	active_check_radius = 128

[patrol]
	spawn_leader = true
	min_pillagers = 4
	max_pillagers = 7
	special_chance = 0.75
	special_amount = 2
	special_illagers = ["minecraft:vindicator", "minecraft:evoker", "minecraft:witch", "takesapillage:archer", "takesapillage:skirmisher", "takesapillage:legioner", "savage_and_ravage:griefer", "savage_and_ravage:executioner", "savage_and_ravage:iceologer", "savage_and_ravage:trickster"]
	target_player_immediately = true
	persistent_patrol_mobs = true

[campaigns]
	enabled = true
	region_size_chunks = 8
	stale_region_ticks = 120000
	base_scan_interval_ticks = 200
	campaign_tick_interval = 100
	campaign_speed_ticks_per_chunk = 80
	max_campaigns_per_base = 4
	max_satellites_per_major_base = 4
	replace_natural_outpost_spawns = true
	structure_base_ids = ["minecraft:pillager_outpost", "takesapillage:bastille", "takesapillage:pillager_camp", "towns_and_towers:exclusives/pillager_outpost_classic", "towns_and_towers:exclusives/pillager_outpost_iberian", "towns_and_towers:exclusives/pillager_outpost_mediterranean", "towns_and_towers:exclusives/pillager_outpost_oriental", "towns_and_towers:exclusives/pillager_outpost_rustic", "towns_and_towers:exclusives/pillager_outpost_swedish", "towns_and_towers:exclusives/pillager_outpost_tudor", "towns_and_towers:pillager_outpost_badlands", "towns_and_towers:pillager_outpost_beach", "towns_and_towers:pillager_outpost_birch_forest", "towns_and_towers:pillager_outpost_desert", "towns_and_towers:pillager_outpost_flower_forest", "towns_and_towers:pillager_outpost_forest", "towns_and_towers:pillager_outpost_grove", "towns_and_towers:pillager_outpost_jungle", "towns_and_towers:pillager_outpost_meadow", "towns_and_towers:pillager_outpost_mushroom_fields", "towns_and_towers:pillager_outpost_old_growth_taiga", "towns_and_towers:pillager_outpost_savanna", "towns_and_towers:pillager_outpost_savanna_plateau", "towns_and_towers:pillager_outpost_snowy_beach", "towns_and_towers:pillager_outpost_snowy_plains", "towns_and_towers:pillager_outpost_snowy_slopes", "towns_and_towers:pillager_outpost_snowy_taiga", "towns_and_towers:pillager_outpost_sparse_jungle", "towns_and_towers:pillager_outpost_sunflower_plains", "towns_and_towers:pillager_outpost_swamp", "towns_and_towers:pillager_outpost_taiga", "towns_and_towers:pillager_outpost_wooded_badlands"]
	death_flags_per_kill = 5
	max_death_flags_per_chunk = 12
	officer_escape_health = 0.22
	officer_engineering_enabled = true
	officer_engineering_cooldown_ticks = 30
	officer_engineering_ttl_ticks = 6000
	officer_engineering_max_blocks = 24
