#KubeJS Dev Properties
#Fri May 01 15:34:01 AEST 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=false
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
