#!/usr/bin/env python3
import json
import os
import shutil
import signal
import subprocess
import sys
import time
from contextlib import contextmanager
from pathlib import Path

from pack_mod_source import bundled_mod_jar_patterns

ROOT = Path(os.environ.get("ROOT", "/home/gerald/obelisks"))
SERVER_DIR = ROOT / "server-instance"
LIVE_MC = Path(os.environ.get(
    "LIVE_MC",
    "/home/gerald/.local/share/PrismLauncher/instances/Bound to Matter-Playtest 3 - v1/minecraft",
))
OUT_ROOT = Path(os.environ.get("OUT_ROOT", "/tmp/btm-c2me-feature-matrix"))
PORT = int(os.environ.get("SERVER_PORT", "25565"))

BASE_VALUES = {
    "optimize_async_chunk_request": False,
    "enforce_safe_world_random_access": False,
    "threaded_worldgen_enabled": False,
    "threaded_worldgen_allow_features": False,
    "threaded_worldgen_reduce_lock_radius": False,
    "threaded_worldgen_async_scheduling": False,
    "io_async": False,
    "no_tick_view_distance": False,
}

VARIANTS = {
    "baseline": {},
    "no_tick_view_distance": {"no_tick_view_distance": True},
    "io_async": {"io_async": True},
    "async_chunk_request": {"optimize_async_chunk_request": True},
    "threaded_worldgen_no_features": {
        "threaded_worldgen_enabled": True,
        "threaded_worldgen_allow_features": False,
        "threaded_worldgen_reduce_lock_radius": False,
        "threaded_worldgen_async_scheduling": False,
    },
    "threaded_worldgen_async_scheduling": {
        "threaded_worldgen_enabled": True,
        "threaded_worldgen_allow_features": False,
        "threaded_worldgen_reduce_lock_radius": False,
        "threaded_worldgen_async_scheduling": True,
    },
    "threaded_worldgen_features": {
        "threaded_worldgen_enabled": True,
        "threaded_worldgen_allow_features": True,
        "threaded_worldgen_reduce_lock_radius": True,
        "threaded_worldgen_async_scheduling": True,
    },
    "safe_world_random_enforcement": {"enforce_safe_world_random_access": True},
    "all_risky_features": {
        "optimize_async_chunk_request": True,
        "enforce_safe_world_random_access": True,
        "threaded_worldgen_enabled": True,
        "threaded_worldgen_allow_features": True,
        "threaded_worldgen_reduce_lock_radius": True,
        "threaded_worldgen_async_scheduling": True,
        "io_async": True,
        "no_tick_view_distance": True,
    },
}

CUSTOM_MOD_JARS = bundled_mod_jar_patterns(ROOT)


def bool_string(value: bool) -> str:
    return "true" if value else "false"


def render_config(overrides: dict[str, bool]) -> str:
    values = dict(BASE_VALUES)
    values.update(overrides)
    return f'''version = 3

# Generated by tools/c2me_feature_matrix.py.
# C2ME is required for the finished pack; risky features are re-enabled one
# group at a time and must pass tools/client_join_probe.sh.
defaultGlobalExecutorParallelismExpression = "default"
globalExecutorParallelism = "default"

[generalOptimizations]
\tmidTickChunkTasksInterval = "default"
\toptimizeAsyncChunkRequest = "{bool_string(values["optimize_async_chunk_request"])}"

\t[generalOptimizations.autoSave]
\t\tmode = "default"
\t\tdelay = "default"

[fixes]
\tdisableLoggingShutdownHook = "default"
\tenforceSafeWorldRandomAccess = "{bool_string(values["enforce_safe_world_random_access"])}"

[threadedWorldGen]
\tenabled = "{bool_string(values["threaded_worldgen_enabled"])}"
\tallowThreadedFeatures = "{bool_string(values["threaded_worldgen_allow_features"])}"
\treduceLockRadius = "{bool_string(values["threaded_worldgen_reduce_lock_radius"])}"
\tasyncScheduling = "{bool_string(values["threaded_worldgen_async_scheduling"])}"

[ioSystem]
\treplaceImpl = "default"
\tasync = "{bool_string(values["io_async"])}"
\tgcFreeChunkSerializer = "default"
\tchunkDataCacheSoftLimit = "default"
\tchunkDataCacheLimit = "default"
\tchunkStreamVersion = "default"

[noTickViewDistance]
\tenabled = "{bool_string(values["no_tick_view_distance"])}"
\tmaxConcurrentChunkLoads = "default"
\tcompatibilityMode = "default"
\tensureChunkCorrectness = "default"

[clientSideConfig]

\t[clientSideConfig.modifyMaxVDConfig]
\t\tenabled = "default"
\t\tmaxViewDistance = "default"

[vanillaWorldGenOptimizations]
\toptimizeAquifer = false
\tuseEndBiomeCache = "default"
'''


def run(cmd: list[str], cwd: Path = ROOT, timeout: int | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, timeout=timeout)


def sync_config(config_text: str) -> None:
    targets = [
        ROOT / "config" / "c2me.toml",
        SERVER_DIR / "config" / "c2me.toml",
        ROOT / "server-template" / "config" / "c2me.toml",
        LIVE_MC / "config" / "c2me.toml",
        LIVE_MC / "server-template" / "config" / "c2me.toml",
    ]
    for target in targets:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(config_text)


@contextmanager
def temporarily_disable_mods(mod_ids: list[str], run_dir: Path):
    disabled: list[tuple[Path, Path]] = []
    mod_dirs = [SERVER_DIR / "mods", LIVE_MC / "mods"]
    try:
        for mod_id in mod_ids:
            patterns = CUSTOM_MOD_JARS.get(mod_id)
            if patterns is None:
                raise ValueError(f"Unknown custom mod id for isolation: {mod_id}")
            for mod_dir in mod_dirs:
                for pattern in patterns:
                    for jar in sorted(mod_dir.glob(pattern)):
                        disabled_path = jar.with_name(jar.name + ".c2me-isolation-disabled")
                        if disabled_path.exists():
                            raise RuntimeError(f"Refusing to overwrite existing disabled jar: {disabled_path}")
                        jar.rename(disabled_path)
                        disabled.append((disabled_path, jar))
        if disabled:
            (run_dir / "disabled-mods.txt").write_text(
                "\n".join(f"{disabled_path} -> {jar}" for disabled_path, jar in disabled) + "\n"
            )
        yield
    finally:
        for disabled_path, jar in reversed(disabled):
            if disabled_path.exists():
                disabled_path.rename(jar)


def server_listening() -> bool:
    result = run(["ss", "-ltn"], timeout=5)
    return f":{PORT}" in result.stdout


def wait_for_server(log_path: Path, timeout_sec: int) -> tuple[bool, str]:
    start = time.time()
    while time.time() - start < timeout_sec:
        if log_path.exists():
            text = log_path.read_text(errors="replace")
            if "Done (" in text and server_listening():
                return True, "ready"
            if "Encountered an unexpected exception" in text or "This crash report has been saved" in text:
                return False, "server_fatal_log_signature"
        if server_listening():
            return True, "listening"
        time.sleep(2)
    return False, "server_start_timeout"


def stop_server(proc: subprocess.Popen, timeout_sec: int = 60) -> None:
    if proc.poll() is not None:
        return
    try:
        proc.stdin.write("stop\n")
        proc.stdin.flush()
    except Exception:
        pass
    try:
        proc.wait(timeout=timeout_sec)
        return
    except subprocess.TimeoutExpired:
        proc.terminate()
    try:
        proc.wait(timeout=10)
        return
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=10)


def copy_if_exists(src: Path, dst: Path) -> None:
    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def analyze_failure(run_dir: Path) -> dict[str, list[str]]:
    patterns = {
        "c2me_random_thread": ["CheckedThreadLocalRandom", "handleNotOwner"],
        "login_chunk_wait": ["PlayerRespawnLogic", "beforeAwaitChunk", "ServerChunkCache"],
        "structure_worldgen": ["Structure", "worldgen", "feature", "placement"],
        "dh": ["DistantHorizons", "Distant Horizons"],
        "villagewalls": ["villagewalls", "VillageWall"],
        "settlementroads": ["settlementroads", "SettlementRoad"],
        "modernfix_c2me": ["ModernFix", "c2me"],
    }
    hits: dict[str, list[str]] = {}
    for log in run_dir.glob("**/*.log"):
        text = log.read_text(errors="replace")
        for key, needles in patterns.items():
            found = [needle for needle in needles if needle in text]
            if found:
                hits.setdefault(key, []).append(log.name)
    return hits


def run_variant(name: str, overrides: dict[str, bool], matrix_dir: Path) -> dict[str, object]:
    variant_dir = matrix_dir / name
    variant_dir.mkdir(parents=True, exist_ok=True)
    disabled_mods = [
        mod_id.strip()
        for mod_id in os.environ.get("C2ME_DISABLED_MODS", "").split(",")
        if mod_id.strip()
    ]
    config_text = render_config(overrides)
    (variant_dir / "c2me.toml").write_text(config_text)
    sync_config(config_text)

    latest_log = SERVER_DIR / "logs" / "latest.log"
    if latest_log.exists():
        latest_log.unlink()

    result: dict[str, object] = {
        "variant": name,
        "overrides": overrides,
        "disabled_mods": disabled_mods,
        "status": "UNKNOWN",
        "reason": "",
    }
    server_out = None
    proc = None
    try:
        with temporarily_disable_mods(disabled_mods, variant_dir):
            server_out = (variant_dir / "server-console.log").open("w")
            proc = subprocess.Popen(
                ["./run.sh", "nogui"],
                cwd=SERVER_DIR,
                text=True,
                stdin=subprocess.PIPE,
                stdout=server_out,
                stderr=subprocess.STDOUT,
            )
            ready, reason = wait_for_server(latest_log, int(os.environ.get("SERVER_BOOT_TIMEOUT_SEC", "180")))
            if not ready:
                result["status"] = "FAIL"
                result["reason"] = reason
                return result

            probe_env = (
                "START_TIMEOUT_SEC=${C2ME_PROBE_START_TIMEOUT_SEC:-180} "
                "JOIN_TIMEOUT_SEC=${C2ME_PROBE_JOIN_TIMEOUT_SEC:-480} "
                "SETTLE_SEC=${C2ME_PROBE_SETTLE_SEC:-30} "
                "KEEP_CLIENT=0 tools/client_join_probe.sh"
            )
            probe = run(["bash", "-lc", probe_env], cwd=ROOT, timeout=700)
            (variant_dir / "probe.stdout").write_text(probe.stdout)
            (variant_dir / "probe.stderr").write_text(probe.stderr)
            result["probe_returncode"] = probe.returncode
            result["status"] = "PASS" if probe.returncode == 0 else "FAIL"
            reason_line = next((line for line in probe.stdout.splitlines() if line.startswith("reason=")), "")
            result["reason"] = reason_line.removeprefix("reason=") if reason_line else "probe_failed"
            run_dir_line = next((line for line in probe.stdout.splitlines() if line.startswith("run_dir=")), "")
            if run_dir_line:
                result["probe_run_dir"] = run_dir_line.removeprefix("run_dir=")
    finally:
        if proc is not None:
            stop_server(proc)
        if server_out is not None:
            server_out.close()
        copy_if_exists(latest_log, variant_dir / "server-latest.log")
        crash_dir = SERVER_DIR / "crash-reports"
        if crash_dir.exists():
            for crash in sorted(crash_dir.glob("crash-*-server.txt"), key=lambda p: p.stat().st_mtime, reverse=True)[:3]:
                copy_if_exists(crash, variant_dir / crash.name)

    if result["status"] != "PASS":
        result["analysis_hits"] = analyze_failure(variant_dir)
    return result


def main() -> int:
    selected = os.environ.get("C2ME_VARIANTS")
    names = [name.strip() for name in selected.split(",")] if selected else list(VARIANTS.keys())
    unknown = [name for name in names if name not in VARIANTS]
    if unknown:
        print(f"Unknown variants: {', '.join(unknown)}", file=sys.stderr)
        return 2

    matrix_dir = OUT_ROOT / time.strftime("%Y%m%d-%H%M%S")
    matrix_dir.mkdir(parents=True, exist_ok=True)
    results = []
    try:
        for name in names:
            print(f"== {name} ==", flush=True)
            result = run_variant(name, VARIANTS[name], matrix_dir)
            results.append(result)
            print(json.dumps(result, indent=2), flush=True)
    finally:
        sync_config(render_config({}))

    summary = {"matrix_dir": str(matrix_dir), "results": results}
    (matrix_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    lines = ["# C2ME Feature Matrix", "", f"Matrix dir: `{matrix_dir}`", ""]
    for result in results:
        lines.append(f"- `{result['variant']}`: {result['status']} ({result.get('reason', '')})")
    (matrix_dir / "summary.md").write_text("\n".join(lines) + "\n")
    print(json.dumps(summary, indent=2))
    return 0 if all(result["status"] == "PASS" for result in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
