// RPGStats typed heart definitions used as Blood Magic orb keys.
// A Still-Beating Heart is converted by using it with a matching catalyst in the offhand.

if (typeof RPGStatsEvents !== 'undefined') {
    RPGStatsEvents.heartTypes(function (event) {
        event.heartType('kubejs:weak_blood')
            .item('kubejs:weak_blood_heart')
            .asset('rpgstats:item/still_beating_heart')
            .displayName('Blood-Touched Heart')
            .catalyst('bloodmagic:sacrificialdagger')
            .consumeCatalyst(false)
            .channelTime(45)
            .priority(210)
            .requireRitualTierMin(1)

        event.heartType('kubejs:apprentice_blood')
            .item('kubejs:apprentice_blood_heart')
            .asset('rpgstats:item/still_beating_heart')
            .displayName('Levelled Blood Heart')
            .catalyst('bloodmagic:weakbloodorb')
            .consumeCatalyst(false)
            .channelTime(60)
            .priority(220)
            .requireRitualTierMin(1)
            .requireLevelMin(10)

        event.heartType('kubejs:magician_blood')
            .item('kubejs:magician_blood_heart')
            .asset('rpgstats:item/still_beating_heart')
            .displayName('Hemostatic Blood Heart')
            .catalyst('bloodmagic:apprenticebloodorb')
            .consumeCatalyst(false)
            .channelTime(75)
            .priority(230)
            .requireRitualTierMin(2)
            .requireLevelMin(20)
            .requireStatMin('rpgstats:hemostasis', 20)

        event.heartType('kubejs:master_blood')
            .item('kubejs:master_blood_heart')
            .asset('rpgstats:item/still_beating_heart')
            .displayName('Withered Blood Heart')
            .catalyst('bloodmagic:magicianbloodorb')
            .consumeCatalyst(false)
            .channelTime(90)
            .priority(240)
            .requireRitualTierMin(3)
            .requireLevelMin(30)
            .requireStatMin('rpgstats:hemostasis', 28)
            .requireDeathCause('wither')

        event.heartType('kubejs:archmage_blood')
            .item('kubejs:archmage_blood_heart')
            .asset('rpgstats:item/still_beating_heart')
            .displayName('Draconic Blood Heart')
            .catalyst('bloodmagic:masterbloodorb')
            .consumeCatalyst(false)
            .channelTime(110)
            .priority(250)
            .requireRitualTierMin(4)
            .requireLevelMin(40)
            .requireDimension('minecraft:the_end')
            .requireStatMin('rpgstats:hemostasis', 36)
    })
}
